# Artificial Intelligence.
# Grado IngenierÃ­a InformÃ¡tica
# Curso 2017-18
# credit.py

# Data about when a bank should grant a loan to a customer, depending on the
# following attributes:


# * Employment: official, employed, unemployed, retired.
# * Additional financial products contracted: 0, 1 or more than 2
# * Real estate: 0, 1 or more than 2
# * Number of children: 0, 1 or more than 2
# * Marital status: single, married, widowed, divorced.
# * Income: low, medium, high

# The classification attribute indicates if the loan should be granted, not
# granted or the application as to be studied in more detail.


attributes = [("Employment", ["official", "employed", "unemployed", "retired"]),
              ("Products", ["none", "one", "more"]),
              ("Real estate", ["none", "one", "more"]),
              ("Children", ["none", "one", "more"]),
              ("Marital status", ["single", "married", "widowed", "divorced"]),
              ("Income", ["low", "medium", "high"])]

class_name = 'Loan'
classes = ['grant', 'not grant', 'study']

train = [['retired', 'none', 'none', 'one', 'single', 'high', 'study'],
         ['official', 'more', 'none', 'one', 'widowed', 'low', 'not grant'],
         ['unemployed', 'more', 'more', 'one', 'divorced', 'low', 'study'],
         ['official', 'more', 'none', 'more', 'divorced', 'high', 'grant'],
         ['official', 'one', 'more', 'more', 'single', 'high', 'grant'],
         ['unemployed', 'none', 'more', 'more', 'divorced', 'high', 'grant'],
         ['official', 'none', 'none', 'one', 'widowed', 'high', 'grant'],
         ['retired', 'none', 'none', 'more', 'divorced', 'high', 'study'],
         ['official', 'none', 'one', 'one', 'single', 'low', 'study'],
         ['official', 'one', 'one', 'none', 'divorced', 'high', 'grant'],
         ['unemployed', 'more', 'none', 'one', 'married', 'low', 'study'],
         ['official', 'none', 'one', 'none', 'widowed', 'low', 'study'],
         ['official', 'one', 'more', 'one', 'divorced', 'medium', 'grant'],
         ['retired', 'more', 'more', 'one', 'divorced', 'medium', 'grant'],
         ['employed', 'one', 'more', 'more', 'single', 'low', 'not grant'],
         ['retired', 'more', 'none', 'more', 'divorced', 'medium', 'not grant'],
         ['retired', 'more', 'one', 'one', 'married', 'medium', 'not grant'],
         ['official', 'more', 'more', 'one', 'single', 'medium', 'grant'],
         ['retired', 'one', 'none', 'one', 'single', 'medium', 'not grant'],
         ['official', 'one', 'more', 'more', 'married', 'high', 'grant'],
         ['employed', 'one', 'none', 'none', 'divorced', 'medium', 'grant'],
         ['retired', 'none', 'one', 'none', 'divorced', 'medium', 'study'],
         ['employed', 'one', 'none', 'more', 'single', 'medium', 'not grant'],
         ['unemployed', 'one', 'more', 'more', 'single', 'low', 'grant'],
         ['employed', 'more', 'one', 'none', 'divorced', 'high', 'study'],
         ['employed', 'more', 'none', 'one', 'widowed', 'low', 'study'],
         ['official', 'none', 'more', 'none', 'single', 'medium', 'grant'],
         ['official', 'none', 'one', 'more', 'single', 'high', 'grant'],
         ['employed', 'one', 'none', 'one', 'divorced', 'high', 'study'],
         ['retired', 'more', 'none', 'none', 'single', 'high', 'study'],
         ['official', 'none', 'one', 'none', 'single', 'high', 'grant'],
         ['retired', 'more', 'none', 'one', 'married', 'high', 'study'],
         ['employed', 'more', 'none', 'none', 'single', 'high', 'study'],
         ['retired', 'one', 'more', 'more', 'divorced', 'low', 'study'],
         ['unemployed', 'one', 'one', 'one', 'divorced', 'medium', 'study'],
         ['retired', 'one', 'more', 'none', 'single', 'medium', 'grant'],
         ['retired', 'none', 'more', 'none', 'married', 'low', 'study'],
         ['retired', 'one', 'more', 'none', 'married', 'low', 'grant'],
         ['employed', 'none', 'more', 'one', 'married', 'high', 'grant'],
         ['retired', 'one', 'none', 'one', 'single', 'low', 'not grant'],
         ['retired', 'none', 'one', 'one', 'widowed', 'high', 'study'],
         ['retired', 'more', 'none', 'one', 'single', 'high', 'study'],
         ['official', 'none', 'more', 'one', 'married', 'medium', 'grant'],
         ['unemployed', 'one', 'one', 'more', 'widowed', 'low', 'not grant'],
         ['retired', 'none', 'one', 'one', 'married', 'high', 'study'],
         ['employed', 'one', 'one', 'none', 'widowed', 'high', 'grant'],
         ['official', 'more', 'one', 'none', 'widowed', 'high', 'grant'],
         ['unemployed', 'more', 'none', 'none', 'widowed', 'high', 'grant'],
         ['employed', 'none', 'none', 'one', 'married', 'medium', 'study'],
         ['unemployed', 'none', 'more', 'one', 'married', 'low', 'not grant'],
         ['official', 'none', 'more', 'one', 'divorced', 'high', 'grant'],
         ['official', 'one', 'none', 'more', 'divorced', 'medium', 'study'],
         ['retired', 'one', 'more', 'none', 'single', 'low', 'not grant'],
         ['employed', 'none', 'none', 'none', 'widowed', 'medium', 'study'],
         ['unemployed', 'none', 'none', 'more', 'married', 'medium', 'study'],
         ['retired', 'one', 'one', 'more', 'widowed', 'high', 'study'],
         ['official', 'none', 'one', 'one', 'single', 'high', 'grant'],
         ['retired', 'more', 'one', 'one', 'single', 'high', 'study'],
         ['retired', 'more', 'none', 'one', 'married', 'medium', 'not grant'],
         ['retired', 'more', 'none', 'one', 'widowed', 'medium', 'not grant'],
         ['unemployed', 'none', 'one', 'none', 'widowed', 'medium', 'grant'],
         ['unemployed', 'more', 'more', 'none', 'divorced', 'high', 'grant'],
         ['unemployed', 'none', 'none', 'more', 'widowed', 'medium', 'study'],
         ['official', 'none', 'more', 'more', 'widowed', 'high', 'grant'],
         ['retired', 'none', 'one', 'more', 'single', 'medium', 'not grant'],
         ['unemployed', 'more', 'none', 'one', 'single', 'medium', 'not grant'],
         ['official', 'none', 'more', 'none', 'single', 'high', 'grant'],
         ['employed', 'one', 'one', 'one', 'single', 'low', 'not grant'],
         ['unemployed', 'more', 'one', 'more', 'married', 'low', 'not grant'],
         ['unemployed', 'more', 'one', 'one', 'widowed', 'medium', 'study'],
         ['employed', 'one', 'more', 'none', 'divorced', 'high', 'grant'],
         ['unemployed', 'none', 'more', 'one', 'married', 'high', 'study'],
         ['employed', 'none', 'more', 'more', 'single', 'low', 'not grant'],
         ['unemployed', 'more', 'more', 'more', 'widowed', 'low', 'not grant'],
         ['official', 'one', 'none', 'none', 'divorced', 'low', 'not grant'],
         ['retired', 'more', 'more', 'one', 'married', 'medium', 'grant'],
         ['official', 'more', 'more', 'none', 'married', 'high', 'grant'],
         ['unemployed', 'one', 'none', 'one', 'single', 'low', 'not grant'],
         ['retired', 'more', 'one', 'more', 'widowed', 'high', 'study'],
         ['retired', 'one', 'none', 'more', 'married', 'high', 'study'],
         ['retired', 'none', 'none', 'none', 'widowed', 'low', 'not grant'],
         ['retired', 'none', 'one', 'none', 'single', 'medium', 'not grant'],
         ['unemployed', 'one', 'one', 'more', 'single', 'low', 'not grant'],
         ['unemployed', 'none', 'one', 'none', 'married', 'high', 'study'],
         ['retired', 'none', 'none', 'one', 'single', 'medium', 'not grant'],
         ['employed', 'one', 'more', 'one', 'married', 'low', 'not grant'],
         ['employed', 'more', 'none', 'more', 'single', 'low', 'study'],
         ['unemployed', 'none', 'none', 'none', 'single', 'medium', 'not grant'],
         ['employed', 'none', 'more', 'one', 'widowed', 'high', 'grant'],
         ['official', 'more', 'none', 'one', 'married', 'high', 'grant'],
         ['employed', 'more', 'one', 'none', 'divorced', 'low', 'study'],
         ['unemployed', 'more', 'none', 'more', 'single', 'high', 'study'],
         ['employed', 'none', 'more', 'one', 'single', 'high', 'grant'],
         ['employed', 'one', 'more', 'more', 'single', 'high', 'grant'],
         ['employed', 'one', 'more', 'none', 'widowed', 'low', 'not grant'],
         ['retired', 'one', 'more', 'one', 'widowed', 'low', 'not grant'],
         ['retired', 'one', 'more', 'none', 'divorced', 'low', 'not grant'],
         ['retired', 'one', 'more', 'one', 'divorced', 'high', 'study'],
         ['retired', 'one', 'more', 'one', 'married', 'high', 'study'],
         ['retired', 'none', 'more', 'more', 'single', 'high', 'study'],
         ['official', 'none', 'more', 'more', 'widowed', 'low', 'study'],
         ['employed', 'none', 'one', 'more', 'widowed', 'high', 'grant'],
         ['official', 'one', 'one', 'one', 'widowed', 'medium', 'study'],
         ['unemployed', 'more', 'none', 'one', 'married', 'medium', 'not grant'],
         ['unemployed', 'one', 'none', 'more', 'divorced', 'high', 'study'],
         ['official', 'more', 'more', 'none', 'widowed', 'low', 'study'],
         ['official', 'one', 'none', 'more', 'widowed', 'low', 'not grant'],
         ['official', 'none', 'one', 'none', 'divorced', 'high', 'grant'],
         ['official', 'none', 'none', 'more', 'widowed', 'medium', 'study'],
         ['employed', 'none', 'none', 'none', 'single', 'medium', 'study'],
         ['retired', 'one', 'more', 'none', 'married', 'high', 'study'],
         ['unemployed', 'one', 'one', 'one', 'widowed', 'low', 'not grant'],
         ['official', 'none', 'more', 'none', 'married', 'medium', 'grant'],
         ['official', 'one', 'more', 'none', 'single', 'medium', 'grant'],
         ['unemployed', 'one', 'one', 'none', 'widowed', 'medium', 'study'],
         ['employed', 'more', 'more', 'more', 'married', 'low', 'study'],
         ['employed', 'more', 'one', 'one', 'single', 'medium', 'study'],
         ['retired', 'none', 'more', 'more', 'divorced', 'medium', 'grant'],
         ['official', 'more', 'more', 'none', 'divorced', 'high', 'grant'],
         ['retired', 'more', 'none', 'one', 'widowed', 'low', 'not grant'],
         ['official', 'more', 'one', 'none', 'single', 'low', 'study'],
         ['retired', 'none', 'one', 'more', 'married', 'high', 'study'],
         ['official', 'one', 'none', 'none', 'divorced', 'medium', 'study'],
         ['employed', 'one', 'one', 'none', 'divorced', 'medium', 'study'],
         ['employed', 'one', 'more', 'more', 'single', 'medium', 'grant'],
         ['official', 'more', 'more', 'more', 'widowed', 'medium', 'grant'],
         ['unemployed', 'more', 'none', 'one', 'divorced', 'high', 'study'],
         ['unemployed', 'none', 'more', 'more', 'single', 'high', 'study'],
         ['retired', 'none', 'more', 'more', 'divorced', 'low', 'not grant'],
         ['unemployed', 'none', 'more', 'more', 'divorced', 'medium', 'grant'],
         ['unemployed', 'none', 'one', 'one', 'widowed', 'high', 'study'],
         ['employed', 'one', 'one', 'none', 'widowed', 'medium', 'study'],
         ['employed', 'none', 'none', 'more', 'single', 'low', 'not grant'],
         ['unemployed', 'none', 'one', 'more', 'divorced', 'medium', 'not grant'],
         ['employed', 'one', 'one', 'more', 'married', 'low', 'not grant'],
         ['retired', 'none', 'more', 'one', 'married', 'high', 'study'],
         ['unemployed', 'more', 'one', 'one', 'widowed', 'high', 'study'],
         ['unemployed', 'none', 'one', 'none', 'divorced', 'high', 'study'],
         ['employed', 'one', 'one', 'more', 'single', 'medium', 'study'],
         ['employed', 'one', 'one', 'one', 'divorced', 'medium', 'study'],
         ['unemployed', 'more', 'none', 'none', 'married', 'medium', 'not grant'],
         ['official', 'more', 'none', 'one', 'married', 'low', 'not grant'],
         ['official', 'one', 'more', 'none', 'single', 'low', 'grant'],
         ['unemployed', 'more', 'none', 'none', 'single', 'high', 'study'],
         ['official', 'more', 'none', 'none', 'widowed', 'low', 'not grant'],
         ['unemployed', 'one', 'none', 'more', 'divorced', 'low', 'not grant'],
         ['unemployed', 'none', 'none', 'more', 'divorced', 'medium', 'not grant'],
         ['official', 'one', 'more', 'more', 'married', 'medium', 'grant'],
         ['employed', 'more', 'one', 'one', 'single', 'low', 'study'],
         ['employed', 'more', 'more', 'one', 'widowed', 'high', 'grant'],
         ['retired', 'more', 'none', 'none', 'married', 'high', 'study'],
         ['retired', 'none', 'one', 'none', 'divorced', 'high', 'study'],
         ['unemployed', 'none', 'none', 'one', 'married', 'low', 'not grant'],
         ['unemployed', 'one', 'none', 'more', 'single', 'low', 'not grant'],
         ['unemployed', 'none', 'one', 'one', 'single', 'low', 'not grant'],
         ['employed', 'none', 'none', 'one', 'widowed', 'high', 'grant'],
         ['retired', 'more', 'one', 'none', 'divorced', 'low', 'not grant'],
         ['official', 'more', 'none', 'more', 'widowed', 'high', 'grant'],
         ['retired', 'none', 'none', 'one', 'widowed', 'high', 'study'],
         ['official', 'more', 'one', 'more', 'single', 'medium', 'not grant'],
         ['unemployed', 'one', 'none', 'none', 'divorced', 'medium', 'not grant'],
         ['retired', 'one', 'more', 'one', 'widowed', 'medium', 'grant'],
         ['retired', 'none', 'none', 'more', 'widowed', 'low', 'not grant'],
         ['unemployed', 'none', 'one', 'none', 'divorced', 'low', 'not grant'],
         ['official', 'one', 'more', 'one', 'widowed', 'high', 'grant'],
         ['retired', 'one', 'one', 'more', 'single', 'low', 'not grant'],
         ['official', 'one', 'more', 'one', 'widowed', 'medium', 'grant'],
         ['unemployed', 'more', 'one', 'none', 'single', 'high', 'study'],
         ['retired', 'none', 'none', 'none', 'single', 'high', 'study'],
         ['retired', 'more', 'more', 'more', 'married', 'medium', 'grant'],
         ['unemployed', 'more', 'none', 'one', 'widowed', 'medium', 'not grant'],
         ['unemployed', 'more', 'one', 'one', 'married', 'high', 'study'],
         ['unemployed', 'more', 'one', 'one', 'divorced', 'medium', 'study'],
         ['retired', 'one', 'more', 'one', 'married', 'medium', 'grant'],
         ['employed', 'one', 'more', 'more', 'married', 'high', 'grant'],
         ['unemployed', 'none', 'none', 'one', 'married', 'medium', 'not grant'],
         ['unemployed', 'none', 'one', 'none', 'single', 'high', 'study'],
         ['unemployed', 'none', 'none', 'more', 'single', 'high', 'study'],
         ['unemployed', 'one', 'one', 'one', 'married', 'medium', 'study'],
         ['unemployed', 'none', 'more', 'one', 'divorced', 'low', 'not grant'],
         ['unemployed', 'one', 'more', 'more', 'widowed', 'medium', 'grant'],
         ['retired', 'one', 'one', 'more', 'single', 'medium', 'study'],
         ['unemployed', 'one', 'none', 'more', 'widowed', 'high', 'study'],
         ['employed', 'none', 'one', 'more', 'married', 'low', 'not grant'],
         ['retired', 'more', 'none', 'one', 'widowed', 'high', 'study'],
         ['unemployed', 'none', 'none', 'one', 'divorced', 'low', 'not grant'],
         ['official', 'none', 'none', 'one', 'divorced', 'high', 'grant'],
         ['employed', 'one', 'one', 'one', 'single', 'medium', 'study'],
         ['retired', 'one', 'none', 'more', 'single', 'medium', 'not grant'],
         ['retired', 'more', 'none', 'more', 'single', 'low', 'not grant'],
         ['unemployed', 'one', 'more', 'more', 'widowed', 'high', 'study'],
         ['unemployed', 'one', 'one', 'one', 'widowed', 'medium', 'study'],
         ['official', 'one', 'more', 'one', 'married', 'low', 'grant'],
         ['employed', 'one', 'one', 'more', 'divorced', 'low', 'not grant'],
         ['employed', 'none', 'more', 'one', 'married', 'low', 'not grant'],
         ['unemployed', 'more', 'more', 'none', 'married', 'medium', 'grant'],
         ['unemployed', 'one', 'none', 'one', 'divorced', 'high', 'study'],
         ['employed', 'one', 'more', 'one', 'single', 'low', 'not grant'],
         ['employed', 'more', 'none', 'one', 'married', 'low', 'study'],
         ['employed', 'none', 'none', 'none', 'divorced', 'high', 'grant'],
         ['unemployed', 'more', 'one', 'none', 'married', 'high', 'study'],
         ['unemployed', 'one', 'one', 'more', 'married', 'low', 'not grant'],
         ['official', 'none', 'more', 'none', 'single', 'low', 'grant'],
         ['official', 'none', 'more', 'one', 'widowed', 'medium', 'grant'],
         ['official', 'more', 'more', 'none', 'single', 'low', 'grant'],
         ['unemployed', 'more', 'none', 'more', 'widowed', 'low', 'not grant'],
         ['retired', 'none', 'none', 'more', 'single', 'medium', 'not grant'],
         ['employed', 'one', 'one', 'one', 'married', 'high', 'grant'],
         ['unemployed', 'more', 'none', 'more', 'divorced', 'low', 'not grant'],
         ['official', 'one', 'none', 'more', 'divorced', 'low', 'not grant'],
         ['retired', 'one', 'none', 'more', 'divorced', 'high', 'study'],
         ['employed', 'one', 'none', 'more', 'single', 'high', 'grant'],
         ['employed', 'one', 'one', 'one', 'widowed', 'high', 'grant'],
         ['employed', 'more', 'none', 'more', 'single', 'medium', 'study'],
         ['unemployed', 'none', 'more', 'one', 'widowed', 'high', 'study'],
         ['retired', 'none', 'none', 'none', 'married', 'low', 'not grant'],
         ['official', 'more', 'none', 'more', 'single', 'high', 'grant'],
         ['employed', 'none', 'more', 'more', 'married', 'medium', 'grant'],
         ['retired', 'one', 'none', 'one', 'divorced', 'low', 'not grant'],
         ['unemployed', 'one', 'none', 'one', 'single', 'high', 'study'],
         ['unemployed', 'more', 'one', 'none', 'widowed', 'high', 'study'],
         ['official', 'none', 'none', 'more', 'single', 'medium', 'study'],
         ['unemployed', 'none', 'one', 'more', 'married', 'low', 'not grant'],
         ['official', 'none', 'one', 'none', 'widowed', 'high', 'grant'],
         ['unemployed', 'more', 'one', 'none', 'widowed', 'medium', 'study'],
         ['employed', 'one', 'one', 'none', 'married', 'low', 'not grant'],
         ['unemployed', 'one', 'more', 'one', 'divorced', 'low', 'not grant'],
         ['unemployed', 'more', 'one', 'more', 'widowed', 'low', 'not grant'],
         ['unemployed', 'one', 'none', 'none', 'single', 'medium', 'not grant'],
         ['official', 'more', 'more', 'none', 'widowed', 'medium', 'grant'],
         ['retired', 'more', 'one', 'more', 'divorced', 'medium', 'not grant'],
         ['unemployed', 'none', 'none', 'one', 'divorced', 'medium', 'not grant'],
         ['official', 'more', 'more', 'more', 'single', 'high', 'grant'],
         ['retired', 'more', 'more', 'more', 'widowed', 'low', 'not grant'],
         ['unemployed', 'one', 'none', 'more', 'married', 'high', 'study'],
         ['unemployed', 'none', 'more', 'none', 'single', 'low', 'not grant'],
         ['unemployed', 'one', 'more', 'none', 'married', 'medium', 'grant'],
         ['official', 'more', 'more', 'one', 'divorced', 'medium', 'grant'],
         ['official', 'more', 'more', 'one', 'widowed', 'low', 'grant'],
         ['employed', 'none', 'one', 'one', 'single', 'high', 'grant'],
         ['official', 'one', 'one', 'one', 'single', 'low', 'study'],
         ['official', 'none', 'one', 'none', 'single', 'low', 'study'],
         ['unemployed', 'one', 'none', 'more', 'married', 'medium', 'not grant'],
         ['retired', 'one', 'none', 'more', 'widowed', 'low', 'not grant'],
         ['retired', 'none', 'none', 'one', 'widowed', 'low', 'not grant'],
         ['unemployed', 'one', 'more', 'none', 'single', 'low', 'not grant'],
         ['employed', 'more', 'one', 'more', 'single', 'low', 'study'],
         ['employed', 'none', 'one', 'none', 'single', 'medium', 'not grant'],
         ['employed', 'more', 'more', 'none', 'married', 'medium', 'grant'],
         ['employed', 'more', 'one', 'none', 'divorced', 'medium', 'study'],
         ['employed', 'none', 'more', 'more', 'divorced', 'high', 'grant'],
         ['retired', 'none', 'none', 'more', 'married', 'high', 'study'],
         ['unemployed', 'one', 'one', 'one', 'married', 'high', 'study'],
         ['official', 'more', 'none', 'none', 'widowed', 'medium', 'study'],
         ['employed', 'one', 'more', 'one', 'widowed', 'high', 'grant'],
         ['employed', 'none', 'none', 'none', 'married', 'medium', 'study'],
         ['official', 'more', 'none', 'more', 'married', 'high', 'grant'],
         ['unemployed', 'one', 'one', 'none', 'single', 'low', 'not grant'],
         ['official', 'more', 'more', 'none', 'married', 'medium', 'grant'],
         ['employed', 'none', 'none', 'one', 'divorced', 'high', 'grant'],
         ['official', 'more', 'more', 'one', 'divorced', 'high', 'grant'],
         ['employed', 'one', 'one', 'none', 'single', 'low', 'not grant'],
         ['official', 'more', 'more', 'more', 'widowed', 'low', 'grant'],
         ['employed', 'none', 'more', 'none', 'divorced', 'high', 'grant'],
         ['retired', 'one', 'one', 'one', 'widowed', 'medium', 'study'],
         ['unemployed', 'more', 'one', 'one', 'married', 'medium', 'study'],
         ['employed', 'none', 'none', 'none', 'married', 'low', 'not grant'],
         ['employed', 'one', 'more', 'more', 'married', 'medium', 'grant'],
         ['official', 'none', 'one', 'one', 'single', 'medium', 'not grant'],
         ['official', 'one', 'more', 'one', 'married', 'medium', 'grant'],
         ['retired', 'more', 'one', 'more', 'married', 'low', 'not grant'],
         ['unemployed', 'more', 'none', 'more', 'married', 'medium', 'not grant'],
         ['unemployed', 'none', 'one', 'more', 'married', 'medium', 'not grant'],
         ['retired', 'one', 'one', 'none', 'married', 'medium', 'study'],
         ['official', 'more', 'one', 'none', 'single', 'high', 'grant'],
         ['retired', 'one', 'one', 'more', 'single', 'high', 'study'],
         ['official', 'more', 'none', 'one', 'single', 'low', 'not grant'],
         ['retired', 'more', 'more', 'none', 'single', 'low', 'not grant'],
         ['official', 'more', 'more', 'one', 'single', 'low', 'grant'],
         ['employed', 'more', 'one', 'one', 'divorced', 'medium', 'study'],
         ['employed', 'one', 'one', 'one', 'single', 'high', 'grant'],
         ['official', 'one', 'more', 'one', 'married', 'high', 'grant'],
         ['official', 'more', 'none', 'one', 'single', 'medium', 'study'],
         ['official', 'none', 'none', 'one', 'married', 'low', 'not grant'],
         ['unemployed', 'none', 'none', 'one', 'married', 'high', 'study'],
         ['employed', 'none', 'one', 'one', 'divorced', 'low', 'not grant'],
         ['unemployed', 'none', 'none', 'one', 'divorced', 'high', 'study'],
         ['retired', 'more', 'more', 'more', 'divorced', 'low', 'not grant'],
         ['retired', 'none', 'more', 'one', 'widowed', 'medium', 'grant'],
         ['employed', 'more', 'one', 'more', 'divorced', 'high', 'grant'],
         ['employed', 'more', 'one', 'one', 'divorced', 'high', 'grant'],
         ['official', 'none', 'none', 'more', 'divorced', 'low', 'not grant'],
         ['unemployed', 'none', 'one', 'one', 'married', 'high', 'study'],
         ['retired', 'none', 'none', 'none', 'single', 'low', 'not grant'],
         ['unemployed', 'more', 'none', 'none', 'divorced', 'medium', 'not grant'],
         ['retired', 'one', 'one', 'none', 'single', 'high', 'study'],
         ['employed', 'one', 'more', 'one', 'divorced', 'medium', 'grant'],
         ['employed', 'none', 'one', 'none', 'divorced', 'high', 'grant'],
         ['employed', 'more', 'more', 'none', 'single', 'medium', 'grant'],
         ['unemployed', 'one', 'more', 'none', 'divorced', 'high', 'study'],
         ['unemployed', 'none', 'none', 'more', 'divorced', 'high', 'study'],
         ['official', 'none', 'one', 'none', 'divorced', 'low', 'study'],
         ['employed', 'none', 'none', 'more', 'widowed', 'low', 'not grant'],
         ['retired', 'none', 'one', 'none', 'widowed', 'low', 'not grant'],
         ['retired', 'none', 'more', 'more', 'married', 'high', 'study'],
         ['retired', 'more', 'more', 'one', 'single', 'high', 'study'],
         ['employed', 'none', 'more', 'more', 'divorced', 'low', 'not grant'],
         ['retired', 'more', 'more', 'none', 'widowed', 'low', 'not grant'],
         ['unemployed', 'none', 'one', 'one', 'widowed', 'medium', 'not grant'],
         ['retired', 'none', 'more', 'one', 'married', 'medium', 'grant'],
         ['unemployed', 'none', 'none', 'one', 'widowed', 'high', 'study'],
         ['official', 'one', 'more', 'more', 'widowed', 'low', 'grant'],
         ['retired', 'one', 'one', 'none', 'widowed', 'medium', 'study'],
         ['retired', 'more', 'one', 'more', 'widowed', 'low', 'not grant'],
         ['retired', 'more', 'one', 'none', 'divorced', 'high', 'study'],
         ['employed', 'more', 'one', 'more', 'widowed', 'medium', 'not grant'],
         ['unemployed', 'more', 'more', 'more', 'single', 'medium', 'grant'],
         ['retired', 'one', 'none', 'none', 'divorced', 'medium', 'not grant'],
         ['employed', 'one', 'none', 'more', 'married', 'high', 'grant'],
         ['unemployed', 'more', 'none', 'none', 'married', 'low', 'not grant'],
         ['employed', 'more', 'one', 'one', 'single', 'high', 'grant'],
         ['employed', 'none', 'more', 'one', 'widowed', 'medium', 'grant'],
         ['employed', 'none', 'none', 'one', 'widowed', 'medium', 'study'],
         ['official', 'none', 'more', 'more', 'divorced', 'low', 'grant'],
         ['retired', 'none', 'none', 'more', 'widowed', 'medium', 'not grant']]

valid = [['unemployed', 'one', 'none', 'none', 'married', 'low', 'not grant'],
         ['employed', 'one', 'none', 'none', 'widowed', 'medium', 'study'],
         ['official', 'none', 'none', 'none', 'divorced', 'high', 'grant'],
         ['employed', 'none', 'one', 'none', 'divorced', 'medium', 'not grant'],
         ['unemployed', 'more', 'one', 'more', 'married', 'medium', 'not grant'],
         ['unemployed', 'one', 'one', 'none', 'divorced', 'medium', 'study'],
         ['employed', 'none', 'more', 'more', 'widowed', 'low', 'not grant'],
         ['official', 'more', 'one', 'none', 'widowed', 'low', 'study'],
         ['official', 'more', 'one', 'none', 'married', 'high', 'grant'],
         ['employed', 'more', 'none', 'more', 'widowed', 'high', 'grant'],
         ['employed', 'one', 'none', 'none', 'widowed', 'low', 'not grant'],
         ['official', 'more', 'more', 'one', 'widowed', 'high', 'grant'],
         ['employed', 'one', 'more', 'more', 'widowed', 'high', 'grant'],
         ['employed', 'more', 'one', 'one', 'widowed', 'high', 'grant'],
         ['unemployed', 'one', 'one', 'more', 'single', 'medium', 'study'],
         ['retired', 'none', 'one', 'more', 'widowed', 'low', 'not grant'],
         ['official', 'none', 'more', 'one', 'divorced', 'low', 'grant'],
         ['unemployed', 'one', 'one', 'none', 'widowed', 'high', 'study'],
         ['unemployed', 'more', 'one', 'none', 'divorced', 'low', 'not grant'],
         ['retired', 'more', 'one', 'one', 'single', 'low', 'not grant'],
         ['official', 'none', 'more', 'none', 'married', 'high', 'grant'],
         ['retired', 'none', 'none', 'none', 'married', 'high', 'study'],
         ['official', 'more', 'one', 'more', 'divorced', 'medium', 'not grant'],
         ['official', 'one', 'none', 'one', 'single', 'high', 'grant'],
         ['unemployed', 'more', 'more', 'none', 'widowed', 'low', 'not grant'],
         ['employed', 'none', 'none', 'none', 'divorced', 'low', 'not grant'],
         ['official', 'more', 'none', 'one', 'widowed', 'medium', 'study'],
         ['unemployed', 'one', 'one', 'more', 'divorced', 'low', 'not grant'],
         ['employed', 'more', 'more', 'one', 'single', 'high', 'grant'],
         ['unemployed', 'more', 'none', 'none', 'single', 'medium', 'not grant'],
         ['official', 'one', 'none', 'one', 'single', 'medium', 'study'],
         ['official', 'none', 'none', 'more', 'single', 'high', 'grant'],
         ['official', 'one', 'more', 'none', 'married', 'medium', 'grant'],
         ['official', 'more', 'none', 'none', 'divorced', 'low', 'not grant'],
         ['unemployed', 'none', 'one', 'more', 'married', 'high', 'study'],
         ['retired', 'none', 'none', 'more', 'married', 'low', 'not grant'],
         ['unemployed', 'one', 'one', 'none', 'married', 'high', 'study'],
         ['employed', 'more', 'one', 'none', 'single', 'medium', 'study'],
         ['unemployed', 'none', 'more', 'none', 'widowed', 'medium', 'grant'],
         ['official', 'one', 'one', 'one', 'married', 'medium', 'study'],
         ['employed', 'one', 'more', 'none', 'married', 'medium', 'grant'],
         ['retired', 'one', 'one', 'one', 'divorced', 'medium', 'study'],
         ['unemployed', 'one', 'more', 'none', 'widowed', 'medium', 'grant'],
         ['employed', 'more', 'none', 'more', 'widowed', 'medium', 'study'],
         ['official', 'none', 'more', 'one', 'widowed', 'high', 'grant'],
         ['retired', 'more', 'none', 'none', 'widowed', 'low', 'not grant'],
         ['retired', 'one', 'more', 'one', 'divorced', 'low', 'not grant'],
         ['official', 'one', 'more', 'one', 'widowed', 'low', 'grant'],
         ['retired', 'more', 'none', 'none', 'married', 'low', 'not grant'],
         ['retired', 'one', 'one', 'one', 'divorced', 'low', 'not grant'],
         ['employed', 'none', 'more', 'one', 'single', 'medium', 'grant'],
         ['employed', 'more', 'none', 'one', 'widowed', 'high', 'grant'],
         ['employed', 'more', 'none', 'one', 'divorced', 'high', 'grant'],
         ['retired', 'one', 'none', 'one', 'married', 'low', 'not grant'],
         ['unemployed', 'more', 'one', 'none', 'single', 'medium', 'study'],
         ['retired', 'none', 'more', 'one', 'widowed', 'low', 'not grant'],
         ['unemployed', 'more', 'more', 'more', 'divorced', 'medium', 'grant'],
         ['retired', 'more', 'more', 'more', 'married', 'low', 'not grant'],
         ['retired', 'one', 'more', 'none', 'married', 'medium', 'grant'],
         ['unemployed', 'one', 'more', 'more', 'single', 'medium', 'grant'],
         ['unemployed', 'one', 'more', 'more', 'married', 'medium', 'grant'],
         ['retired', 'more', 'more', 'one', 'widowed', 'low', 'not grant'],
         ['unemployed', 'none', 'one', 'more', 'single', 'high', 'study'],
         ['official', 'more', 'none', 'none', 'married', 'medium', 'study'],
         ['employed', 'more', 'more', 'more', 'married', 'medium', 'grant'],
         ['official', 'one', 'one', 'none', 'widowed', 'high', 'grant'],
         ['retired', 'none', 'one', 'more', 'widowed', 'medium', 'not grant'],
         ['retired', 'more', 'more', 'none', 'single', 'medium', 'grant'],
         ['unemployed', 'more', 'more', 'none', 'married', 'low', 'not grant'],
         ['unemployed', 'one', 'none', 'none', 'single', 'low', 'not grant'],
         ['employed', 'more', 'none', 'more', 'divorced', 'high', 'grant'],
         ['retired', 'none', 'none', 'one', 'married', 'high', 'study'],
         ['official', 'one', 'none', 'none', 'married', 'low', 'not grant'],
         ['retired', 'one', 'more', 'one', 'single', 'low', 'not grant'],
         ['retired', 'more', 'one', 'none', 'single', 'high', 'study'],
         ['retired', 'none', 'more', 'more', 'single', 'medium', 'grant'],
         ['official', 'none', 'one', 'more', 'married', 'low', 'study'],
         ['retired', 'more', 'more', 'none', 'divorced', 'medium', 'grant'],
         ['official', 'one', 'one', 'more', 'single', 'low', 'study'],
         ['retired', 'more', 'none', 'none', 'single', 'medium', 'not grant'],
         ['employed', 'one', 'one', 'more', 'married', 'high', 'grant'],
         ['employed', 'more', 'one', 'more', 'single', 'medium', 'not grant'],
         ['retired', 'more', 'none', 'none', 'married', 'medium', 'not grant'],
         ['unemployed', 'none', 'one', 'more', 'widowed', 'high', 'study'],
         ['official', 'more', 'one', 'one', 'divorced', 'medium', 'study'],
         ['retired', 'one', 'more', 'more', 'widowed', 'low', 'not grant'],
         ['employed', 'more', 'more', 'more', 'divorced', 'medium', 'grant'],
         ['official', 'more', 'one', 'one', 'widowed', 'medium', 'study'],
         ['retired', 'none', 'one', 'one', 'single', 'low', 'not grant'],
         ['official', 'more', 'none', 'more', 'single', 'low', 'not grant'],
         ['employed', 'none', 'one', 'none', 'single', 'high', 'grant'],
         ['employed', 'none', 'one', 'none', 'married', 'high', 'grant'],
         ['retired', 'more', 'one', 'one', 'single', 'medium', 'study'],
         ['official', 'one', 'none', 'one', 'widowed', 'low', 'not grant'],
         ['retired', 'more', 'one', 'more', 'married', 'high', 'study'],
         ['unemployed', 'none', 'more', 'more', 'widowed', 'high', 'study'],
         ['retired', 'none', 'more', 'none', 'single', 'high', 'study'],
         ['official', 'none', 'one', 'none', 'married', 'low', 'study'],
         ['retired', 'more', 'more', 'more', 'widowed', 'high', 'study'],
         ['official', 'one', 'none', 'one', 'married', 'medium', 'study'],
         ['official', 'one', 'one', 'more', 'married', 'medium', 'study'],
         ['retired', 'one', 'none', 'more', 'divorced', 'medium', 'not grant'],
         ['unemployed', 'more', 'one', 'more', 'single', 'low', 'not grant'],
         ['unemployed', 'one', 'more', 'one', 'widowed', 'medium', 'grant'],
         ['retired', 'none', 'none', 'one', 'divorced', 'high', 'study'],
         ['official', 'more', 'none', 'none', 'single', 'medium', 'study'],
         ['official', 'more', 'one', 'more', 'widowed', 'high', 'grant'],
         ['official', 'none', 'more', 'more', 'widowed', 'medium', 'grant'],
         ['official', 'none', 'none', 'none', 'divorced', 'low', 'not grant'],
         ['employed', 'none', 'one', 'one', 'married', 'medium', 'not grant'],
         ['official', 'none', 'more', 'more', 'single', 'medium', 'grant'],
         ['employed', 'one', 'one', 'one', 'divorced', 'low', 'not grant'],
         ['retired', 'more', 'none', 'more', 'widowed', 'high', 'study'],
         ['unemployed', 'more', 'one', 'more', 'married', 'high', 'study'],
         ['unemployed', 'more', 'one', 'more', 'single', 'medium', 'not grant'],
         ['employed', 'none', 'none', 'more', 'married', 'high', 'grant'],
         ['employed', 'none', 'one', 'more', 'widowed', 'medium', 'not grant'],
         ['retired', 'one', 'none', 'one', 'divorced', 'high', 'study'],
         ['official', 'more', 'more', 'none', 'divorced', 'medium', 'grant'],
         ['official', 'more', 'one', 'one', 'widowed', 'low', 'study'],
         ['unemployed', 'one', 'more', 'none', 'single', 'high', 'study'],
         ['unemployed', 'one', 'none', 'none', 'divorced', 'high', 'study'],
         ['employed', 'none', 'more', 'none', 'divorced', 'low', 'not grant'],
         ['unemployed', 'one', 'more', 'more', 'widowed', 'low', 'not grant'],
         ['employed', 'more', 'none', 'none', 'single', 'low', 'study'],
         ['unemployed', 'none', 'one', 'one', 'single', 'medium', 'not grant'],
         ['unemployed', 'more', 'none', 'none', 'widowed', 'medium', 'not grant'],
         ['employed', 'more', 'one', 'one', 'married', 'medium', 'study'],
         ['retired', 'more', 'more', 'none', 'single', 'high', 'study'],
         ['retired', 'more', 'none', 'more', 'married', 'high', 'study'],
         ['employed', 'none', 'more', 'none', 'single', 'low', 'not grant'],
         ['official', 'more', 'none', 'one', 'divorced', 'medium', 'study'],
         ['unemployed', 'one', 'none', 'none', 'married', 'medium', 'not grant'],
         ['employed', 'none', 'none', 'none', 'divorced', 'medium', 'study'],
         ['employed', 'more', 'one', 'one', 'married', 'high', 'grant'],
         ['unemployed', 'none', 'more', 'none', 'married', 'medium', 'grant'],
         ['retired', 'more', 'none', 'one', 'divorced', 'medium', 'not grant'],
         ['unemployed', 'none', 'one', 'none', 'divorced', 'medium', 'not grant'],
         ['employed', 'more', 'one', 'none', 'single', 'high', 'grant'],
         ['retired', 'more', 'more', 'more', 'single', 'high', 'study'],
         ['official', 'more', 'one', 'more', 'single', 'low', 'study'],
         ['official', 'none', 'one', 'one', 'married', 'medium', 'not grant'],
         ['employed', 'one', 'one', 'none', 'married', 'medium', 'study'],
         ['retired', 'one', 'none', 'more', 'widowed', 'medium', 'not grant'],
         ['unemployed', 'more', 'more', 'none', 'single', 'high', 'study'],
         ['official', 'more', 'more', 'one', 'single', 'high', 'grant'],
         ['retired', 'one', 'none', 'one', 'divorced', 'medium', 'not grant'],
         ['official', 'none', 'none', 'one', 'single', 'high', 'grant'],
         ['official', 'more', 'more', 'none', 'single', 'high', 'grant'],
         ['retired', 'one', 'one', 'none', 'widowed', 'high', 'study'],
         ['employed', 'none', 'none', 'more', 'divorced', 'medium', 'study'],
         ['unemployed', 'one', 'more', 'none', 'widowed', 'high', 'study'],
         ['employed', 'none', 'one', 'one', 'single', 'medium', 'not grant'],
         ['employed', 'one', 'one', 'more', 'single', 'low', 'not grant'],
         ['employed', 'more', 'one', 'one', 'married', 'low', 'study'],
         ['official', 'one', 'one', 'one', 'widowed', 'high', 'grant'],
         ['unemployed', 'none', 'more', 'none', 'divorced', 'low', 'not grant'],
         ['employed', 'one', 'none', 'none', 'married', 'low', 'not grant'],
         ['official', 'none', 'more', 'more', 'married', 'medium', 'grant'],
         ['employed', 'one', 'more', 'one', 'divorced', 'high', 'grant'],
         ['employed', 'more', 'more', 'one', 'divorced', 'low', 'study'],
         ['official', 'one', 'more', 'none', 'widowed', 'low', 'grant']]

test = [['official', 'none', 'more', 'none', 'divorced', 'medium', 'grant'],
        ['official', 'one', 'more', 'more', 'divorced', 'low', 'grant'],
        ['employed', 'more', 'one', 'none', 'married', 'medium', 'study'],
        ['retired', 'one', 'none', 'none', 'widowed', 'low', 'study'],
        ['employed', 'more', 'more', 'one', 'married', 'medium', 'grant'],
        ['employed', 'more', 'more', 'one', 'married', 'high', 'grant'],
        ['unemployed', 'none', 'one', 'more', 'divorced', 'high', 'study'],
        ['unemployed', 'one', 'more', 'one', 'married', 'medium', 'grant'],
        ['employed', 'one', 'one', 'one', 'married', 'medium', 'study'],
        ['employed', 'one', 'none', 'more', 'divorced', 'low', 'not grant'],
        ['employed', 'one', 'more', 'one', 'single', 'medium', 'grant'],
        ['retired', 'one', 'more', 'more', 'married', 'medium', 'grant'],
        ['unemployed', 'none', 'one', 'one', 'widowed', 'low', 'not grant'],
        ['unemployed', 'more', 'more', 'none', 'widowed', 'high', 'study'],
        ['official', 'none', 'none', 'none', 'single', 'medium', 'study'],
        ['official', 'none', 'one', 'one', 'widowed', 'low', 'study'],
        ['official', 'none', 'none', 'none', 'single', 'low', 'not grant'],
        ['retired', 'none', 'more', 'none', 'single', 'low', 'not grant'],
        ['unemployed', 'none', 'more', 'none', 'divorced', 'high', 'study'],
        ['retired', 'more', 'more', 'one', 'married', 'low', 'not grant'],
        ['official', 'one', 'none', 'more', 'widowed', 'high', 'grant'],
        ['employed', 'one', 'none', 'none', 'divorced', 'low', 'not grant'],
        ['employed', 'one', 'none', 'more', 'single', 'low', 'not grant'],
        ['retired', 'none', 'one', 'more', 'single', 'low', 'not grant'],
        ['unemployed', 'none', 'none', 'one', 'widowed', 'low', 'not grant'],
        ['official', 'one', 'none', 'none', 'widowed', 'low', 'not grant'],
        ['unemployed', 'none', 'more', 'more', 'single', 'medium', 'grant'],
        ['unemployed', 'none', 'none', 'none', 'single', 'high', 'study'],
        ['unemployed', 'none', 'more', 'more', 'widowed', 'low', 'not grant'],
        ['retired', 'none', 'none', 'more', 'single', 'high', 'study'],
        ['retired', 'one', 'more', 'none', 'single', 'high', 'study'],
        ['unemployed', 'none', 'more', 'one', 'married', 'medium', 'grant'],
        ['employed', 'none', 'more', 'more', 'married', 'high', 'grant'],
        ['unemployed', 'one', 'none', 'one', 'single', 'medium', 'not grant'],
        ['employed', 'none', 'more', 'none', 'single', 'medium', 'grant'],
        ['official', 'one', 'none', 'more', 'married', 'high', 'grant'],
        ['official', 'more', 'more', 'more', 'divorced', 'low', 'grant'],
        ['retired', 'none', 'one', 'more', 'divorced', 'low', 'not grant'],
        ['unemployed', 'one', 'more', 'none', 'single', 'medium', 'grant'],
        ['retired', 'none', 'none', 'more', 'widowed', 'high', 'study'],
        ['official', 'more', 'none', 'one', 'widowed', 'high', 'grant'],
        ['unemployed', 'none', 'none', 'one', 'single', 'medium', 'not grant'],
        ['employed', 'none', 'one', 'one', 'single', 'low', 'not grant'],
        ['employed', 'more', 'one', 'more', 'married', 'medium', 'not grant'],
        ['employed', 'more', 'none', 'none', 'widowed', 'medium', 'study'],
        ['employed', 'one', 'more', 'more', 'divorced', 'low', 'not grant'],
        ['official', 'one', 'none', 'more', 'single', 'medium', 'study'],
        ['retired', 'more', 'none', 'none', 'single', 'low', 'not grant'],
        ['retired', 'more', 'one', 'none', 'married', 'low', 'not grant'],
        ['employed', 'none', 'more', 'more', 'single', 'high', 'grant'],
        ['official', 'none', 'more', 'one', 'married', 'high', 'grant'],
        ['employed', 'none', 'none', 'one', 'single', 'medium', 'study'],
        ['employed', 'one', 'none', 'more', 'divorced', 'medium', 'study'],
        ['official', 'more', 'one', 'none', 'married', 'low', 'study'],
        ['employed', 'more', 'one', 'none', 'widowed', 'low', 'study'],
        ['employed', 'one', 'none', 'one', 'married', 'high', 'grant'],
        ['retired', 'none', 'one', 'more', 'divorced', 'high', 'study'],
        ['employed', 'more', 'more', 'none', 'divorced', 'high', 'grant'],
        ['retired', 'one', 'none', 'none', 'single', 'high', 'study'],
        ['employed', 'none', 'more', 'none', 'single', 'high', 'grant'],
        ['unemployed', 'more', 'none', 'one', 'single', 'high', 'study'],
        ['unemployed', 'more', 'one', 'none', 'married', 'medium', 'study'],
        ['official', 'more', 'more', 'more', 'widowed', 'high', 'grant'],
        ['retired', 'more', 'one', 'more', 'divorced', 'low', 'not grant'],
        ['retired', 'more', 'more', 'none', 'married', 'medium', 'grant'],
        ['employed', 'one', 'none', 'one', 'single', 'medium', 'study'],
        ['employed', 'one', 'one', 'more', 'single', 'high', 'grant'],
        ['unemployed', 'none', 'one', 'none', 'single', 'medium', 'study'],
        ['unemployed', 'none', 'none', 'more', 'single', 'medium', 'not grant'],
        ['employed', 'more', 'more', 'more', 'widowed', 'low', 'study'],
        ['retired', 'more', 'one', 'none', 'widowed', 'medium', 'study'],
        ['official', 'one', 'more', 'one', 'single', 'medium', 'grant'],
        ['retired', 'one', 'more', 'one', 'single', 'medium', 'grant'],
        ['unemployed', 'none', 'one', 'none', 'widowed', 'high', 'study'],
        ['unemployed', 'more', 'none', 'none', 'divorced', 'low', 'not grant'],
        ['employed', 'none', 'none', 'one', 'divorced', 'medium', 'study'],
        ['official', 'one', 'more', 'one', 'divorced', 'low', 'grant'],
        ['employed', 'one', 'none', 'none', 'single', 'low', 'not grant'],
        ['retired', 'more', 'none', 'more', 'widowed', 'low', 'not grant'],
        ['retired', 'none', 'one', 'more', 'married', 'low', 'not grant'],
        ['employed', 'more', 'more', 'more', 'divorced', 'low', 'study'],
        ['unemployed', 'more', 'more', 'none', 'divorced', 'low', 'not grant'],
        ['employed', 'more', 'more', 'one', 'divorced', 'medium', 'grant'],
        ['official', 'one', 'one', 'more', 'married', 'low', 'study'],
        ['official', 'one', 'more', 'none', 'divorced', 'low', 'grant'],
        ['official', 'more', 'none', 'more', 'widowed', 'medium', 'study'],
        ['employed', 'none', 'none', 'none', 'single', 'high', 'grant'],
        ['official', 'none', 'more', 'none', 'divorced', 'low', 'grant'],
        ['unemployed', 'more', 'more', 'more', 'widowed', 'high', 'study'],
        ['retired', 'more', 'more', 'none', 'married', 'high', 'study'],
        ['unemployed', 'one', 'none', 'more', 'widowed', 'low', 'not grant'],
        ['employed', 'more', 'one', 'one', 'widowed', 'low', 'study'],
        ['employed', 'one', 'none', 'more', 'widowed', 'medium', 'study'],
        ['retired', 'none', 'one', 'none', 'widowed', 'medium', 'not grant'],
        ['unemployed', 'one', 'one', 'none', 'married', 'low', 'not grant'],
        ['official', 'one', 'none', 'one', 'married', 'high', 'grant'],
        ['employed', 'none', 'one', 'one', 'divorced', 'high', 'grant'],
        ['retired', 'one', 'none', 'none', 'single', 'medium', 'not grant'],
        ['official', 'none', 'more', 'one', 'single', 'high', 'grant'],
        ['employed', 'none', 'one', 'one', 'married', 'low', 'not grant'],
        ['employed', 'more', 'more', 'one', 'married', 'low', 'study'],
        ['unemployed', 'one', 'more', 'none', 'married', 'high', 'study'],
        ['official', 'more', 'more', 'more', 'divorced', 'high', 'grant'],
        ['retired', 'more', 'one', 'one', 'widowed', 'high', 'study'],
        ['employed', 'one', 'one', 'none', 'widowed', 'low', 'not grant'],
        ['official', 'one', 'one', 'one', 'divorced', 'high', 'grant'],
        ['retired', 'one', 'none', 'more', 'widowed', 'high', 'study'],
        ['official', 'none', 'one', 'more', 'single', 'medium', 'not grant'],
        ['retired', 'one', 'more', 'none', 'divorced', 'high', 'study'],
        ['retired', 'none', 'none', 'none', 'married', 'medium', 'not grant'],
        ['unemployed', 'none', 'one', 'one', 'divorced', 'medium', 'not grant'],
        ['employed', 'none', 'one', 'more', 'married', 'medium', 'not grant'],
        ['retired', 'one', 'more', 'none', 'divorced', 'medium', 'grant'],
        ['retired', 'none', 'one', 'none', 'single', 'low', 'not grant'],
        ['unemployed', 'none', 'one', 'none', 'married', 'medium', 'not grant'],
        ['unemployed', 'one', 'none', 'one', 'married', 'medium', 'not grant'],
        ['retired', 'one', 'one', 'none', 'single', 'low', 'not grant'],
        ['unemployed', 'more', 'more', 'more', 'married', 'low', 'not grant'],
        ['official', 'none', 'one', 'one', 'widowed', 'medium', 'not grant'],
        ['retired', 'more', 'none', 'more', 'widowed', 'medium', 'not grant'],
        ['retired', 'more', 'more', 'one', 'widowed', 'high', 'study'],
        ['retired', 'more', 'more', 'more', 'single', 'medium', 'grant'],
        ['unemployed', 'more', 'none', 'one', 'divorced', 'low', 'not grant'],
        ['employed', 'more', 'more', 'none', 'single', 'high', 'grant'],
        ['retired', 'none', 'more', 'more', 'widowed', 'high', 'study'],
        ['employed', 'one', 'none', 'none', 'single', 'medium', 'study'],
        ['retired', 'more', 'none', 'none', 'widowed', 'medium', 'not grant'],
        ['retired', 'none', 'more', 'one', 'single', 'high', 'study'],
        ['official', 'none', 'none', 'more', 'married', 'medium', 'study'],
        ['retired', 'more', 'none', 'none', 'divorced', 'medium', 'not grant'],
        ['unemployed', 'more', 'none', 'one', 'married', 'high', 'study'],
        ['retired', 'none', 'one', 'one', 'widowed', 'medium', 'not grant'],
        ['unemployed', 'more', 'more', 'one', 'single', 'medium', 'grant'],
        ['retired', 'more', 'more', 'none', 'widowed', 'medium', 'grant'],
        ['retired', 'more', 'one', 'none', 'married', 'medium', 'study'],
        ['official', 'one', 'one', 'none', 'married', 'high', 'grant'],
        ['official', 'one', 'one', 'more', 'married', 'high', 'grant'],
        ['retired', 'none', 'one', 'none', 'married', 'high', 'study'],
        ['official', 'one', 'one', 'none', 'married', 'medium', 'study'],
        ['retired', 'one', 'none', 'none', 'married', 'high', 'study'],
        ['employed', 'none', 'one', 'more', 'single', 'medium', 'not grant'],
        ['official', 'more', 'one', 'none', 'single', 'medium', 'study'],
        ['unemployed', 'more', 'none', 'one', 'widowed', 'low', 'not grant'],
        ['official', 'more', 'one', 'one', 'single', 'low', 'study'],
        ['retired', 'none', 'more', 'more', 'widowed', 'medium', 'grant'],
        ['employed', 'one', 'none', 'one', 'single', 'high', 'grant'],
        ['employed', 'none', 'one', 'none', 'married', 'low', 'not grant'],
        ['employed', 'one', 'none', 'more', 'widowed', 'low', 'not grant'],
        ['employed', 'one', 'none', 'none', 'divorced', 'high', 'grant'],
        ['unemployed', 'one', 'more', 'more', 'divorced', 'low', 'not grant'],
        ['employed', 'one', 'one', 'one', 'divorced', 'high', 'grant'],
        ['official', 'one', 'one', 'one', 'married', 'low', 'study'],
        ['official', 'none', 'one', 'one', 'divorced', 'low', 'study'],
        ['employed', 'one', 'more', 'more', 'married', 'low', 'not grant'],
        ['unemployed', 'one', 'none', 'one', 'divorced', 'medium', 'not grant'],
        ['employed', 'one', 'none', 'one', 'widowed', 'high', 'grant'],
        ['employed', 'more', 'one', 'none', 'widowed', 'medium', 'study'],
        ['unemployed', 'none', 'none', 'one', 'single', 'high', 'study'],
        ['retired', 'none', 'one', 'one', 'married', 'low', 'not grant'],
        ['retired', 'one', 'none', 'one', 'single', 'high', 'study'],
        ['unemployed', 'one', 'more', 'none', 'divorced', 'low', 'not grant'],
        ['official', 'one', 'more', 'none', 'widowed', 'medium', 'grant'],
        ['official', 'more', 'more', 'more', 'divorced', 'medium', 'grant']]