# Data about when a people survived the titanic


# * sex: 'female', 'male'.
# * pclass: '1st', '3rd', '2nd'
# * age: 'Young', 'Old'

# ------------------------------------
# Attributes:
# ------------------------------------
attributes = [('sex', ['male', 'female']), ('pclass', ['3rd', '1st', '2nd']), ('age', ['Young', 'Old'])]
# ------------------------------------


# Classification attribute
# ------------------------------------
class_name = "Titanic"
# ------------------------------------


# Classes:
# ------------------------------------
classes = ['survived', 'not survived']
# ------------------------------------


# ------------------------------------
# Train set
# ------------------------------------
train = \
    [['female', '3rd', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '2nd', 'Young', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '2nd', 'Young', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Young', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Young', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Young', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Young', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Young', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Young', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Young', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Young', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Young', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Young', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Young', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '2nd', 'Young', 'survived'], ['male', '1st', 'Old', 'survived'], ['female', '2nd', 'Young', 'survived'],
     ['male', '2nd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Young', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Young', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '1st', 'Young', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Young', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Young', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Young', 'survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Young', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Young', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Young', 'survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Young', 'survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Young', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Young', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived']]


# ------------------------------------
#  Validation:
# ------------------------------------
valid = \
    [['female', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Young', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Young', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Young', 'survived'],
     ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Young', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Young', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Young', 'survived'], ['female', '2nd', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Young', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'], ['male', '1st', 'Young', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Young', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived']]


# ------------------------------------
# Test set
# ------------------------------------
test = \
    [['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Young', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'survived'], ['female', '3rd', 'Young', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Young', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Young', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Young', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Young', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '1st', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Young', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Young', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'], ['male', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Young', 'survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '1st', 'Young', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Young', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Young', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Young', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Young', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '2nd', 'Young', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Young', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Young', 'survived'], ['female', '1st', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['female', '1st', 'Old', 'survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '1st', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '2nd', 'Old', 'not survived'], ['male', '1st', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'survived'], ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '1st', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Young', 'not survived'], ['male', '2nd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['female', '1st', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '1st', 'Old', 'not survived'],
     ['female', '3rd', 'Old', 'survived'], ['male', '3rd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '2nd', 'Old', 'survived'], ['male', '3rd', 'Old', 'survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['female', '2nd', 'Young', 'survived'], ['female', '2nd', 'Old', 'survived'],
     ['male', '1st', 'Old', 'not survived'], ['female', '3rd', 'Old', 'survived'],
     ['male', '2nd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '3rd', 'Old', 'not survived'], ['male', '3rd', 'Old', 'not survived'],
     ['male', '2nd', 'Old', 'not survived'], ['female', '3rd', 'Young', 'survived'],
     ['male', '3rd', 'Old', 'not survived']]
